
Config 				  = {}
Config.cooldown		  = 1

-- Add/remove weapon hashes here to be added for holster checks.
Config.Weapons = {
	"WEAPON_PISTOL",
	"WEAPON_COMBATPISTOL",
	"WEAPON_APPISTOL",
	"WEAPON_PISTOL50",
	"WEAPON_SNSPISTOL",
	"WEAPON_HEAVYPISTOL",
	
	"WEAPON_CARBINERIFLE",
	"WEAPON_SMG",
	"WEAPON_COMBATPDW",
	"WEAPON_PUMPSHOTGUN_MK2",
	
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_MARKSMANPISTOL",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_PISTOL_MK2",
	"WEAPON_SNSPISTOL_MK2",
--	"WEAPON_FLAREGUN",
	"WEAPON_STUNGUN",
	"WEAPON_REVOLVER",
	"WEAPON_DAGGER",
	"WEAPON_KNIFE",
	"WEAPON_BOTTLE",
}
